fos_rest:
    param_fetcher_listener: true
    body_listener: true
    view:
        view_response_listener: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    zone:
        - {
            path: ^/api
        }
    format_listener:
        rules:
            - {
                path: ^/api,
                priorities: [ json ],
                fallback_format: json,
                prefer_extension: false
            }
