version: '3.9'
services:
    http:
        image: nginx
        restart: always
        container_name: nginx
        ports:
            - "8002:80"
        volumes:
            - ".:/var/www/html"
            - "./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        restart: always
        container_name: php
        depends_on:
            - db
        command:
            - bash -c "bin/console d:m:m"
        ports:
            - "9000"
        volumes:
            - "./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html"
    db:
        image: postgres:14.5
        container_name: db
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/internal_data
        volumes:
            - "./docker/postgres/conf:/docker-entrypoint-initdb.d"
            - "./db-data:/var/lib/postgresql/data"
        ports:
            - "5435:5432"
