version: '3.9'
services:
    http:
        image: nginx
        container_name: nginx-admin
        ports:
            - "8003:80"
        volumes:
            - ".:/var/www/html"
            - "./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
    php:
        build:
            context: ../
            dockerfile: ./admin/docker/php/Dockerfile
        container_name: php-admin
        env_file: docker/.env
        depends_on:
            - db
        ports:
            - "9001"
        volumes:
            - "./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html"
    db:
        image: postgres:14.5
        container_name: db-admin
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - "./docker/postgres/conf:/docker-entrypoint-initdb.d"
            - "./db-data:/var/lib/postgresql/data"
        ports:
            - "5436:5432"
